#!groovy

pipeline {

  agent {
    label 'node'
  }

  options {
    buildDiscarder(logRotator(numToKeepStr:'20'))
    skipDefaultCheckout()
    disableConcurrentBuilds()
    timeout(time: 60, unit: 'MINUTES')
  }

  stages {

    // --- BUILD ---
    stage('Build') {
      parallel {
        stage('Backend') {
          agent {
            label "node"
          }
          steps {
            deleteDir()
            checkout scm
            sh 'make build-backend'
            sh 'tar cfz backend.tgz api Makefile'
            stash includes: 'backend.tgz', name: 'backend.tgz'
          }
        }
        stage('Frontend') {
          agent {
            label "node"
          }
          steps {
            deleteDir()
            checkout scm
            sh "make build-frontend"
            sh '(cd frontend && tar cfz frontend.tgz locales node_modules cypress public src theme babel.config.js .eslintrc jsconfig.json cypress.json Makefile package.json razzle.config.js yarn.lock)'
            sh 'mv frontend/frontend.tgz ./)'
            stash includes: 'frontend.tgz', name: 'frontend.tgz'
          }
        }
      }
    }

    // Static Code Analysis
    stage('Static Code Analysis') {
      parallel {
        stage('Backend') {
          agent {
            label 'node'
          }
          steps {
            deleteDir()
            checkout scm
            unstash 'backend.tgz'
            sh 'tar xfz backend.tgz'
            sh '(cd api && bin/black  --check src/)'
            sh 'make code-analysis'
            sh 'find . -name flake8.log'
          }
          post {
            always {
              recordIssues enabledForFailure: true, aggregatingResults: true, tool: flake8(pattern: '**/flake8.log')
            }
          }
        }
        stage('Frontend') {
          agent {
            label 'node'
          }
          steps {
            deleteDir()
            checkout scm
            unstash 'frontend.tgz'
            sh '(cd frontend && tar xfz frontend.tgz)'
            sh '(cd frontend && yarn run prettier)'
            sh '(cd frontend && yarn run ci:lint)'
            sh '(cd frontend && cat eslint.xml)'
          }
          post {
            always {
              recordIssues enabledForFailure: true, aggregatingResults: true, tool: esLint(pattern: 'eslint.xml')
            }
          }
        }
      }
    }

    // -- UNIT TESTS ---
    stage('Unit Tests') {
      parallel {
        stage('Backend') {
          agent {
            label 'node'
          }
          steps {
            deleteDir()
            unstash 'backend.tgz'
            sh 'tar xfz backend.tgz'
            sh "make test-backend"
          }
          post {
            always {
              step([
                $class: 'JUnitResultArchiver',
                testResults: 'api/parts/test/testreports/*.xml'
              ])
            }
          }
        }
        stage('Frontend') {
          agent {
            label 'node'
          }
          steps {
            deleteDir()
            unstash 'frontend.tgz'
            sh '(cd frontend && tar xfz frontend.tgz)'
            sh "CI=true make test-frontend"
          }
          post {
            always {
              step([
                $class: 'JUnitResultArchiver',
                testResults: 'frontend/junit.xml'
              ])
            }
          }
        }
      }
    }

    // Acceptance Tests
    stage('Acceptance Tests') {
      agent {
        label 'node'
      }
      steps {
        deleteDir()
        unstash 'backend.tgz'
        sh 'tar xfz backend.tgz'
        unstash 'frontend.tgz'
        sh '(cd frontend && tar xfz frontend.tgz)'
        sh '(cd frontend && yarn cy:install)'
        wrap([$class: 'Xvfb']) {
          sh '(cd frontend && yarn ci:cypress:run)'
        }
      }
      post {
        always {
          archiveArtifacts artifacts: 'frontend/cypress/videos/**/*.mp4', fingerprint: true, allowEmptyArchive: true
          archiveArtifacts artifacts: 'frontend/cypress/screenshots/**/*.png', fingerprint: true, allowEmptyArchive: true
          junit 'frontend/results/cypress-report-*.xml'
        }
      }
    }

    // --- DEPLOYMENT TO {{cookiecutter.repository}} ---
    stage('Deployment to {{cookiecutter.repository}}') {
      parallel {
        stage('Backend') {
          agent {
            label 'kitconcept.io'
          }
          when {
            branch 'main'
          }
          steps {
            sh '(cd /srv/{{cookiecutter.repository}} && git fetch --all && git reset --hard origin/main)'
            sh '(cd /srv/{{cookiecutter.repository}}/api && pm2 stop {{cookiecutter.repository}}-api-dev)'
            sh '(cd /srv/{{cookiecutter.repository}}/api && bin/buildout -c dev.cfg)'
            sh '(cd /srv/{{cookiecutter.repository}}/api && pm2 start {{cookiecutter.repository}}-api-dev)'
          }
        }
        stage('Frontend') {
          agent {
            label 'kitconcept.io'
          }
          when {
            branch 'main'
          }
          steps {
            deleteDir()
            checkout scm
            sh '(cd /srv/{{cookiecutter.repository}}/frontend && yarn install)'
            sh '(cd /srv/{{cookiecutter.repository}}/frontend && PORT=MODIFYME RAZZLE_API_PATH=https://{{cookiecutter.repository}}/api yarn build)'
            sh '(cd /srv/{{cookiecutter.repository}}/frontend && pm2 restart {{cookiecutter.repository}}-volto-dev)'
          }
        }
      }
    }

    // Performance Tests
    stage('Performance Tests') {
      parallel {
        stage('Lighthouse') {
          agent {
            label 'node'
          }
          when {
            branch 'main'
          }
          steps {
            deleteDir()
            checkout scm
            sh '(cd frontend && yarn install)'
            sh '(cd frontend && yarn run lighthouse:ci)'
            sh '(cd frontend && cat lighthouse-report.html | true)'
          }
        }
      }
    }

  }

  post {
    success {
      slackSend (
        channel: "ci",
        color: 'good',
        message: "SUCCESS: #${env.BUILD_NUMBER} ${env.JOB_NAME} (${env.BUILD_URL})"
      )
    }
    failure {
      slackSend (
        channel: "ci",
        color: 'danger',
        message: "FAILURE: #${env.BUILD_NUMBER} ${env.JOB_NAME} (${env.BUILD_URL})"
      )
    }
    unstable {
      slackSend (
        channel: "ci",
        color: 'warning',
        message: "UNSTABLE: #${env.BUILD_NUMBER} ${env.JOB_NAME} (${env.BUILD_URL})"
      )
    }
    aborted {
      slackSend (
        channel: "ci",
        color: 'danger',
        message: "ABORTED: #${env.BUILD_NUMBER} ${env.JOB_NAME} (${env.BUILD_URL})"
      )
    }
    always {
      sh 'rm -rf node_modules *.tgz'
    }
  }
}
